/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '6/8/21 3:08 PM' with Gradle 3.0
 *
 * @author shobha, @date 6/8/21 3:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
