/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '1/8/21 8:05 PM' with Gradle 3.0
 *
 * @author shobha, @date 1/8/21 8:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
