/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '5/8/21 2:00 AM' with Gradle 3.0
 *
 * @author shobha, @date 5/8/21 2:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
