/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '30/7/21 4:38 PM' with Gradle 3.0
 *
 * @author shobha, @date 30/7/21 4:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
