/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '2/8/21 11:07 AM' with Gradle 3.0
 *
 * @author shobha, @date 2/8/21 11:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
