/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '4/8/21 12:51 PM' with Gradle 3.0
 *
 * @author shobha, @date 4/8/21 12:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
