/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '7/8/21 9:49 AM' with Gradle 3.0
 *
 * @author shobha, @date 7/8/21 9:49 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
