/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shobha' at '28/7/21 3:12 PM' with Gradle 3.0
 *
 * @author shobha, @date 28/7/21 3:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
